### ISSUE TITLE
Callback still gets redirected to localhost even though I changed the url to my domain

### ISSUE THREAD

**Issue by DimitrisHousiadas** [jaredhanson/passport-facebook#183]
Hi,

I am using passport-facebook for facebook login in my app, and until recently I was developing it locally, but now I've deployed the app on a server, and when I try to login, facebook still tries to redirect to localhost, even though I've made all the configurations I had to (or at least I think so...)

Concretely, here is how I configure the faceboook strategy

    passport.use(new FacebookStrategy(

        {
            clientID        : '....',
            clientSecret    : '...',
            callbackURL     : 'http://mydomain.com/auth/facebook/callback',
            profileFields   : ...
        },
        ...

And that's how I configure the routing

    app.get('/auth/facebook', passport.authenticate('facebook', {scope: ['email']}));

    app.get('/auth/facebook/callback',
        passport.authenticate('facebook', {session: false, failureRedirect: '/login.html' }),
        function (req, res) {
            res.redirect('/callback.html?token=' + req.user.token + "&userId=" + req.user.userId + "&role=" + req.user.role);
    });

Also, I changed the facebook app settings as following:

![domain](https://cloud.githubusercontent.com/assets/22241908/19514831/ba725e4e-95fd-11e6-95df-86e4ac5048c5.PNG)

![website](https://cloud.githubusercontent.com/assets/22241908/19514842/c5ee9f62-95fd-11e6-8c22-829086e01839.PNG)

![client](https://cloud.githubusercontent.com/assets/22241908/19514852/ce00c1ee-95fd-11e6-9c40-0e1c0b1c1308.PNG)

However, when I try to log in with facebook I get the following error:

![error](https://cloud.githubusercontent.com/assets/22241908/19514993/59a89046-95fe-11e6-9f23-6f84b0605fb0.PNG)

Previously, when instead of mydomain.com I had localhost:3000 everything worked fine.

Any ideas what I am missing? I am also using passport-google-oauth and I have the same issue there as well.

Thanks a lot!

**Comment by riston** [comment]
Hello, I hope you have solved your problem already, but in last screenshot, the URL shows that the `FacebookStrategy` has callback URL some how misconfigured.
```callbackURL     : 'http://mydomain.com/auth/facebook/callback',```

**Comment by DimitrisHousiadas** [comment]
Hi,

thanks for your answer. Not sure though what you mean by misconfigured, to me it seems that the URL is fine.

Is there any chance that it has to do with the fact that I've deployed it with Docker?

**Comment by DimitrisHousiadas** [comment]
Actually, I switched from http to https and now I get redirected correctly, but I get the following error instead:

{"message":"Failed to obtain access token","error":{}}

**Comment by riston** [comment]
Hello, are you sure you get redirected back with access token? Here is quick overview of OAuth2 flow, it's not the passportjs flow but mostly it's same (https://www.soapui.org/oauth2/oauth2-overview.html). This is internal passportjs error, is there also stacktrace? Currently it seems that the access token isn't returned with redirect in query string.

**Comment by DimitrisHousiadas** [comment]
Hi, no the access token is not returned with the redirect, that's the problem and I don't know why.

Thanks a lot for your time!

**Comment by princeajuzie7** [comment]
Am having the same issue in 2024, I've tried everything but still not working
